const tickerMap = {
    'ADA': 'ADAUSD',
    'ALGO' : 'ALGOUSD',
    'ATOM' : 'ATOMUSD',
    'BAT' : 'BATUSD',
    'BCH' : 'BCHUSD',
    'DAI' : 'DAIUSD',
    'DASH' : 'DASHUSD',
    'EOS' : 'EUSUSD',
    'GNO' : 'GNOUSD',
    'ICX' : 'ICXUSD',
    'LINK': 'LINKUSD',
    'LSK' : 'LSKUSD',
    'NANO' : 'NANOUSD',
    'OMG' : 'OMGUSD',
    'OXT':  'OXTUSD',
    'PAXG' : 'PAXGUSD',
    'QTUM' : 'QTUMUSD',
    'SC' : 'SCUSD',
    'TRX' : 'TRXUSD',
    'USDC': 'USDCUSD',
    'USDT' : 'USDTZUSD',
    'WAVE' : 'WAVESUSD',
    'XDG' : 'XDGUSD',
    'ETC' : 'XETCZUSD',
    'ETH' : 'XETHZUSD',
    'LTC' : 'XLTCZUSD',
    'MLN' : 'XMLNZUSD',
    'REP' : 'XREPZUSD',
    'XTZ' : 'XTZUSD',
    'BTC' : 'XXBTZUSD',
    'XLM' : 'XXLMZUSD',
    'XMR' : 'XXMRZUSD',
    'XRP' : 'XXRPZUSD',
    'ZEC' : 'XZECZUSD'
}

module.exports = tickerMap;